### PR TITLE
This ipynb file contains every thing with explanation so no need of r…

### PR DESCRIPTION
**Pull request by praveenarjun**
:red_circle: Title : Eye Disease Classification using RNN
:red_circle: Aim : To develop a model for classifying different eye diseases using Recurrent Neural Networks (RNN).
:red_circle: Brief Explanation : This project aims to build a machine learning model that leverages RNNs to classify various eye diseases from medical images. The model will be trained on a dataset of labeled images and will utilize deep learning techniques to achieve high accuracy. This tool can be valuable for early detection and diagnosis of eye diseases, aiding healthcare professionals in providing timely treatment.

Screenshots 📷
# model accuracy and precision
Screenshot 2024-10-08 at 1 07 27 AM

# model improvement
Screenshot 2024-10-08 at 1 07 53 AM

# model train images
Screenshot 2024-10-08 at 1 08 12 AM

N/A

:white_check_mark: To be Mentioned while taking the issue :  #2 

    Full name :Sree Praveen challa
    What is your participant role? (Mention the Open Source Program name. Gssoc,hackbefest

Happy Contributing 🚀

All the best. Enjoy your open source journey ahead. 😎

### CODE REVIEW

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo:[ https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution](https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution)
Sorry for the inconvenience, and thank you for your understanding! 🙏

**Comment by Ayu-hack** [comment]
Nice project buddy!

**Comment by praveenarjun** [comment]
can u give me a label of gssoc exd in this pr it will increase my score

**Comment by Ayu-hack** [comment]
I am not part of gssoc ext.

**Pull request merged**
