### PR TITLE
Added University Management System written in CPP

### PR DESCRIPTION
**Pull request by LeViiAcKerMan01**
ums

Added project is fully working .

### CODE REVIEW

**Comment by LeViiAcKerMan01** [comment]
I Guess someone reported thisone also...As thisone shows excluded aswell...
I guess someone is targeting you..

**Comment by Ayu-hack** [comment]
No, for now we haven't accepted any PR.

**Comment by Ayu-hack** [comment]
we are helping people to contribute and learning because they are at beginner level. But people are reporting us. They dont need help.

**Comment by LeViiAcKerMan01** [comment]
> No, for now we haven't accepted any PR.

Screenshot 2024-10-07 202915

take a look at this thing...

**Comment by Ayu-hack** [comment]
ohh again.

**Comment by LeViiAcKerMan01** [comment]
> we are helping people to contribute and learning because they are at beginner level. But people are reporting us. They dont need help.

Yeah man.. I don't understand what could be the reason of them reporting on the repos..

**Comment by LeViiAcKerMan01** [comment]
> ohh again.

dunno whats going on...
I have been excluded from each of the repo i have contributed to...
I guess someone is targeting your repos specially..

**Comment by LeViiAcKerMan01** [comment]
> ohh again.

Create a dummy account for the repos and can we connect on linkedin, so that we could get to know the repo in private..
I think someone is keeping track of all the conversations and repos...

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo:[ https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution](https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution)
Sorry for the inconvenience, and thank you for your understanding! 🙏

**Pull request merged**
